<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace App\Modules\Backend\Sign;

use Drago\Database\Entity;
use Nette\SmartObject;


class UsersEntity extends Entity
{
	use SmartObject;

	public const table = 'users';
	public const id = 'id';
	public const username = 'username';
	public const email = 'email';
	public const password = 'password';
	public const token = 'token';

	public int $id;
	public string $username;
	public string $email;
	public string $password;
	public string $token;
}
