<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace App\Modules\Backend\Sign;

use Drago\Database\Entity;


class UsersEntity extends Entity
{
	public const Table = 'users';
	public const Id = 'id';
	public const Username = 'username';
	public const Email = 'email';
	public const Password = 'password';
	public const Token = 'token';

	public int $id;
	public string $username;
	public string $email;
	public string $password;
	public string $token;
}
