<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace App\Services\Entity;

use Drago;
use Nette;


class UsersEntity extends Drago\Database\Entity
{
	use Nette\SmartObject;

	public const TABLE = 'users';
	public const PRIMARY = 'id';
	public const USERNAME = 'username';
	public const EMAIL = 'email';
	public const PASSWORD = 'password';

	public int $id;
	public string $username;
	public string $email;
	public string $password;
}
