<?php

/**
 * This file was generated by Drago Generator.
 *
 * Represents the settings entity in the database.
 */

declare(strict_types=1);

namespace App\Core\Settings;

use Drago\Database\Entity;


/**
 * Represents a row in the 'settings' table of the database.
 * The class provides structure for storing name-value pairs.
 */
class SettingsEntity extends Entity
{
	/**
	 * The name of the table in the database.
	 */
	public const string Table = 'settings';

	/**
	 * The name of the column for the setting name.
	 */
	public const string ColumnName = 'name';

	/**
	 * The name of the column for the setting value.
	 */
	public const string ColumnValue = 'value';

	/**
	 * The name of the setting.
	 */
	public string $name;

	/**
	 * The value of the setting.
	 */
	public string $value;


	public function __construct(string $name, string $value)
	{
		parent::__construct();
		$this->name = $name;
		$this->value = $value;
	}
}
