name: Coding Style

on: [push, pull_request]

jobs:
  nette_cc:
    name: Nette Code Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none

      - id: php-files
        run: |
          if find . -path ./temp -prune -o -name '*.php' -print -quit | grep -q .; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - if: steps.php-files.outputs.exists == 'true'
        run: composer create-project nette/code-checker temp/code-checker ^3 --no-progress
      - if: steps.php-files.outputs.exists == 'true'
        run: php temp/code-checker/code-checker --strict-types --no-progress
      - if: steps.php-files.outputs.exists != 'true'
        run: echo "No PHP files found. Skipping Code Checker."

  nette_cs:
    name: Nette Coding Standard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none

      - id: php-files
        run: |
          if find . -path ./temp -prune -o -name '*.php' -print -quit | grep -q .; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - if: steps.php-files.outputs.exists == 'true'
        run: composer create-project nette/coding-standard temp/coding-standard ^3 --no-progress
      - if: steps.php-files.outputs.exists == 'true'
        run: php temp/coding-standard/ecs check
      - if: steps.php-files.outputs.exists != 'true'
        run: echo "No PHP files found. Skipping Coding Standard."
